# Generated by Django 5.0 on 2024-01-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_remove_buyerprice_name_buyerprice_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprice",
            name="product_id",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.product",
            ),
            preserve_default=False,
        ),
    ]
